"""Helpers for production-safe additive plugin migrations.

Issue #454 reproduces when a database advanced through the
now-deleted post-``0036_add_overwrite_vm_type`` migration lineage (across
the v0.0.15 and develop branches) before the consolidated
``0037_v0_0_15_release`` and its successors landed.  The consolidated
migrations were regenerated by ``makemigrations`` and therefore emit plain
``ALTER TABLE ... ADD COLUMN`` / ``CREATE TABLE`` SQL that aborts with
``psycopg.errors.DuplicateColumn`` (or ``DuplicateTable``) the moment they
hit a column or table the legacy lineage already added.

The helpers below wrap every ``AddField`` and ``CreateModel`` in
``SeparateDatabaseAndState``.  The database side runs a ``RunPython``
callable that introspects the live schema and only invokes
``schema_editor.add_field`` / ``schema_editor.create_model`` when the
target column / table is missing.  The state side keeps the original
``AddField`` / ``CreateModel`` verbatim so Django's project state, model
graph, serializer parity, and ``makemigrations --check`` output are
identical to the non-idempotent original.

Use these helpers for every additive schema operation in the
post-``0036`` chain so the chain is safe to apply against:

  * Clean v0.0.15+ installs (helpers no-op the existence check, then run
    Django's normal schema add).
  * Reporter-style partial-legacy installs (helpers skip the columns or
    tables the legacy lineage already added, then run the rest).
  * Fully-applied legacy installs (the ``replaces`` declaration on
    ``0037_v0_0_15_release`` short-circuits the squash; helpers never run).
"""

from __future__ import annotations

from typing import Any, Callable, Iterable

from django.apps import apps as live_apps
from django.core.exceptions import FieldDoesNotExist
from django.db import migrations
from django.db.migrations.state import ProjectState

APP_LABEL = "netbox_proxbox"


def _table_exists(schema_editor, table: str) -> bool:
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        return table in set(connection.introspection.table_names(cursor))


def _column_exists(schema_editor, table: str, column: str) -> bool:
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        return column in {
            description.name
            for description in connection.introspection.get_table_description(
                cursor, table
            )
        }


def _live_field(model_name: str, field_name: str):
    """Return the fully-bound field from the live model registry, or None.

    The historical apps state passed to ``RunPython`` inside
    ``SeparateDatabaseAndState`` does not include the same operation's
    ``state_operations``, so ``apps.get_model(...).._meta.get_field(name)``
    raises ``FieldDoesNotExist`` for the field being added. The live model
    registry always has the current field with its app/model bindings
    resolved (necessary for ``ForeignKey.target_field`` lookup).
    """
    try:
        model = live_apps.get_model(APP_LABEL, model_name)
    except LookupError:
        return None
    try:
        return model._meta.get_field(field_name)
    except FieldDoesNotExist:
        return None


def _add_field_if_missing(model_name: str, field_name: str) -> Callable:
    def forwards(apps, schema_editor):
        model = apps.get_model(APP_LABEL, model_name)
        field = _live_field(model_name, field_name)
        if field is None:
            return
        if not _table_exists(schema_editor, model._meta.db_table):
            return
        if _column_exists(schema_editor, model._meta.db_table, field.column):
            return
        schema_editor.add_field(model, field)

    return forwards


def _remove_field_if_present(model_name: str, field_name: str) -> Callable:
    def reverse(apps, schema_editor):
        model = apps.get_model(APP_LABEL, model_name)
        field = _live_field(model_name, field_name)
        if field is None:
            return
        if not _table_exists(schema_editor, model._meta.db_table):
            return
        if not _column_exists(schema_editor, model._meta.db_table, field.column):
            return
        schema_editor.remove_field(model, field)

    return reverse


def _model_from_create_state(
    apps,
    model_name: str,
    fields: Iterable[tuple[str, Any]],
    *,
    options: dict | None = None,
    bases: tuple | None = None,
    managers: Iterable | None = None,
):
    """Render the model exactly as this migration's CreateModel defines it."""
    try:
        return apps.get_model(APP_LABEL, model_name)
    except LookupError:
        pass

    state = ProjectState.from_apps(apps)
    state_kwargs: dict[str, Any] = {
        "name": model_name,
        "fields": [(field_name, field.clone()) for field_name, field in fields],
        "options": dict(options or {}),
    }
    if bases is not None:
        state_kwargs["bases"] = bases
    if managers is not None:
        state_kwargs["managers"] = list(managers)
    migrations.CreateModel(**state_kwargs).state_forwards(APP_LABEL, state)
    return state.apps.get_model(APP_LABEL, model_name)


def _create_model_if_missing(
    model_name: str,
    fields: Iterable[tuple[str, Any]],
    *,
    options: dict | None = None,
    bases: tuple | None = None,
    managers: Iterable | None = None,
) -> Callable:
    def forwards(apps, schema_editor):
        model = _model_from_create_state(
            apps,
            model_name,
            fields,
            options=options,
            bases=bases,
            managers=managers,
        )
        if not _table_exists(schema_editor, model._meta.db_table):
            schema_editor.create_model(model)
        for field in model._meta.local_many_to_many:
            through = field.remote_field.through
            if (
                through._meta.auto_created
                and through._meta.db_table.startswith(f"{APP_LABEL}_")
                and not _table_exists(schema_editor, through._meta.db_table)
            ):
                schema_editor.create_model(through)

    return forwards


def _delete_model_if_present(
    model_name: str,
    fields: Iterable[tuple[str, Any]],
    *,
    options: dict | None = None,
    bases: tuple | None = None,
    managers: Iterable | None = None,
) -> Callable:
    def reverse(apps, schema_editor):
        model = _model_from_create_state(
            apps,
            model_name,
            fields,
            options=options,
            bases=bases,
            managers=managers,
        )
        for field in model._meta.local_many_to_many:
            through = field.remote_field.through
            if (
                through._meta.auto_created
                and through._meta.db_table.startswith(f"{APP_LABEL}_")
                and _table_exists(schema_editor, through._meta.db_table)
            ):
                schema_editor.delete_model(through)
        if _table_exists(schema_editor, model._meta.db_table):
            schema_editor.delete_model(model)

    return reverse


def add_field_idempotent(
    model_name: str,
    field_name: str,
    field,
    *,
    preserve_default: bool = True,
) -> migrations.SeparateDatabaseAndState:
    """``AddField`` wrapped to skip the schema change when the column exists."""
    return migrations.SeparateDatabaseAndState(
        database_operations=[
            migrations.RunPython(
                _add_field_if_missing(model_name, field_name),
                reverse_code=_remove_field_if_present(model_name, field_name),
            ),
        ],
        state_operations=[
            migrations.AddField(
                model_name=model_name,
                name=field_name,
                field=field,
                preserve_default=preserve_default,
            ),
        ],
    )


def create_model_idempotent(
    name: str,
    fields: Iterable[tuple[str, Any]],
    *,
    options: dict | None = None,
    bases: tuple | None = None,
    managers: Iterable | None = None,
) -> migrations.SeparateDatabaseAndState:
    """``CreateModel`` wrapped to skip the schema change when the table exists."""
    field_list = list(fields)
    manager_list = list(managers) if managers is not None else None
    state_kwargs: dict[str, Any] = {
        "name": name,
        "fields": field_list,
        "options": options or {},
    }
    if bases is not None:
        state_kwargs["bases"] = bases
    if manager_list is not None:
        state_kwargs["managers"] = manager_list
    return migrations.SeparateDatabaseAndState(
        database_operations=[
            migrations.RunPython(
                _create_model_if_missing(
                    name,
                    field_list,
                    options=options,
                    bases=bases,
                    managers=manager_list,
                ),
                reverse_code=_delete_model_if_present(
                    name,
                    field_list,
                    options=options,
                    bases=bases,
                    managers=manager_list,
                ),
            ),
        ],
        state_operations=[
            migrations.CreateModel(**state_kwargs),
        ],
    )
